#!/usr/bin/env bash
# clode-stack/fork.sh — run a feature-branch CLONE of the stack alongside the
# baseline, isolated in its own Compose project + network + traefik host port.
#
# Subcommands (dispatched from stack.sh):
#   fork <name> --port <p> [--workspaces <f>] [--resolve] [svc...]  create + start a clone
#   fork-down <name>                                     stop + drop a clone (volumes too)
#   fork-ls                                              list running clones
#
# --resolve expands the given services to their dependency closure (via
# scripts/lib/depgraph.py) and auto-enables the profile gates that closure needs,
# plus traefik + whodb. Without it, the listed services (or all) come up as-is.
#
# A clone is `docker compose -p <name>` on network `<name>` with ITS OWN traefik
# on host port <p>. Every service is reached at `http://<svc>.localhost:<p>` and
# the clone's DB viewer at `http://whodb.localhost:<p>`. Only traefik binds a
# host port — datastores are in-network only. Services listed in --workspaces
# build from their feature-branch worktree (image clode-stack/<svc>:<branch>);
# everything else REUSES the baseline image (clode-<svc>:latest) — no rebuild.
#
# The base docker-compose.yml is never edited at runtime — all per-clone config
# is a generated overlay at .forks/<name>.yml.
#
# CLODE_STACK_DIR overrides the canonical stack checkout (whose ../<svc> sibling
# repos + .env files must resolve). Defaults to this script's repo root — set it
# when running the script from a worktree whose ../ has no sibling repos.

set -euo pipefail
SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"   # the scripts/ dir these tools live in
cd "$SCRIPTS_DIR/.."
STACK_DIR="${CLODE_STACK_DIR:-$PWD}"           # canonical checkout for compose + sibling repos

# Datastores / dev-servers whose host-port bindings are stripped in a clone
# (reached in-network only). Keep in sync with the host `ports:` in the compose.
STRIP_PORTS=(db redis databend louie console-web)

die()  { echo "fork: $*" >&2; exit 2; }
info() { echo "==> $*"; }

# ── compose invocation for a clone ──────────────────────────────────────────
# Always run against the canonical checkout so build contexts + env_files
# (../<svc>, ../<svc>/.env) resolve, regardless of where this script lives.
_compose() {
  local name=$1 overlay=$2; shift 2
  docker compose \
    --project-directory "$STACK_DIR" \
    -p "$name" \
    -f "$STACK_DIR/docker-compose.yml" \
    -f "$STACK_DIR/docker-compose.cache.yml" \
    -f "$overlay" \
    "$@"
}

# ── generate the per-clone overlay ──────────────────────────────────────────
# stdin: nothing. args via env: FORK_NAME, FORK_PORT, BUILDABLE_JSON, CHANGED_JSON.
_gen_overlay() {
  FORK_NAME="$1" FORK_PORT="$2" BUILDABLE_JSON="$3" CHANGED_JSON="$4" \
  STRIP_JSON="$(printf '%s\n' "${STRIP_PORTS[@]}" | python3 -c 'import sys,json;print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))')" \
  python3 - <<'PY'
import json, os
name  = os.environ["FORK_NAME"]
port  = os.environ["FORK_PORT"]
build = set(json.loads(os.environ["BUILDABLE_JSON"]))
changed = json.loads(os.environ["CHANGED_JSON"])   # {svc: "clode-stack/svc:branch"}
strip = set(json.loads(os.environ["STRIP_JSON"]))

L = []
L.append(f"# GENERATED by fork.sh for clone '{name}' — do not edit (regenerated each `stack fork`).")
L.append("services:")

# traefik: own network + project constraint (so it routes only THIS clone), own host port.
L += [
    "  traefik:",
    "    command: !override",
    "      - --providers.docker=true",
    "      - --providers.docker.exposedbydefault=false",
    f"      - --providers.docker.network={name}",
    f"      - \"--providers.docker.constraints=Label(`com.docker.compose.project`,`{name}`)\"",
    "      - --entrypoints.web.address=:8080",
    "      - --api.dashboard=true",
    "      - --ping=true",
    "      - --ping.entrypoint=web",
    "      - --log.level=INFO",
    "    ports: !override",
    f"      - \"{port}:8080\"",
]

# datastores that are NOT buildable → strip host ports only (buildable ones get
# their strip folded into the image-pin block below, to avoid a duplicate key).
for svc in sorted(strip - build):
    L += [f"  {svc}:", "    ports: !reset []"]

# every buildable service: reuse the baseline image unless it's a changed one.
for svc in sorted(build):
    L.append(f"  {svc}:")
    if svc in strip:
        L.append("    ports: !reset []")
    L.append(f"    image: {changed.get(svc, f'clode-{svc}:latest')}")

# per-clone DB viewer, wired to this clone's in-network db/redis.
L += [
    "  whodb:",
    "    image: clidey/whodb:latest",
    "    environment:",
    "      WHODB_POSTGRES_1: '{\"alias\":\"pg-brahmi\",\"host\":\"db\",\"user\":\"postgres\",\"password\":\"postgres\",\"database\":\"brahmi\",\"port\":\"5432\"}'",
    "      WHODB_POSTGRES_2: '{\"alias\":\"pg-raksha\",\"host\":\"db\",\"user\":\"postgres\",\"password\":\"postgres\",\"database\":\"raksha\",\"port\":\"5432\"}'",
    "      WHODB_POSTGRES_3: '{\"alias\":\"pg-jumbo\",\"host\":\"db\",\"user\":\"postgres\",\"password\":\"postgres\",\"database\":\"jumbo\",\"port\":\"5432\"}'",
    "      WHODB_REDIS_1: '{\"alias\":\"redis\",\"host\":\"redis\",\"password\":\"clode-redis-local\",\"database\":\"0\",\"port\":\"6379\"}'",
    "    networks: [clode]",
    "    labels:",
    "      - traefik.enable=true",
    "      - \"traefik.http.routers.whodb.rule=Host(`whodb.localhost`)\"",
    "      - traefik.http.services.whodb.loadbalancer.server.port=8080",
    "    restart: unless-stopped",
]

# rename the bridge so this project is a self-contained stack (base pins `name: clode`).
L += ["networks:", "  clode:", f"    name: {name}"]

print("\n".join(L))
PY
}

# ─────────────────────────────────────────────────────────────── fork up ───
cmd_up() {
  local name="" port="" wsfile="" resolve=0 services=()
  while (( $# > 0 )); do
    case "$1" in
      --port)        [[ -n "${2:-}" ]] || die "--port requires a value"; port="$2"; shift 2 ;;
      --port=*)      port="${1#--port=}"; shift ;;
      --workspaces)  [[ -n "${2:-}" ]] || die "--workspaces requires a value"; wsfile="$2"; shift 2 ;;
      --workspaces=*) wsfile="${1#--workspaces=}"; shift ;;
      --resolve)     resolve=1; shift ;;
      -*)            die "unknown flag: $1" ;;
      *)             if [[ -z "$name" ]]; then name="$1"; else services+=("$1"); fi; shift ;;
    esac
  done
  [[ -n "$name" ]] || die "usage: stack fork <name> --port <p> [--workspaces <f>] [svc...]"
  [[ -n "$port" ]] || die "--port <traefik-host-port> is required"
  [[ "$name" == "clode" ]] && die "'clode' is the baseline project — pick another name"
  [[ "$port" =~ ^[0-9]+$ ]] || die "--port must be numeric (got '$port')"

  # workspaces file: default to the repo's workspaces.yaml; make absolute.
  wsfile="${wsfile:-$STACK_DIR/workspaces.yaml}"
  [[ "$wsfile" = /* ]] || wsfile="$PWD/$wsfile"
  [[ -f "$wsfile" ]] || die "workspaces file not found: $wsfile"

  # Resolve build-context overrides. workspaces.sh reads ../<svc> relative to
  # cwd, so resolve from the canonical checkout.
  cd "$STACK_DIR"
  # shellcheck source=scripts/lib/workspaces.sh
  export WORKSPACES_FILE="$wsfile"
  source scripts/lib/workspaces.sh
  resolve_workspaces || die "workspace resolution failed"
  print_workspace_table

  # --resolve: expand the given seeds to their dependency closure and the profile
  # gates that closure needs (scripts/lib/depgraph.py). Turns "clone to test
  # brahmi" into "wake brahmi + everything it needs", with profiles auto-enabled.
  if (( resolve )); then
    (( ${#services[@]} > 0 )) || die "--resolve needs at least one seed service"
    local rj
    rj="$(CLODE_STACK_DIR="$STACK_DIR" "$SCRIPTS_DIR/lib/depgraph.py" resolve "${services[@]}" --json)" \
      || die "dependency resolve failed"
    mapfile -t services < <(printf '%s' "$rj" | python3 -c 'import sys,json;print("\n".join(json.load(sys.stdin)["wake"]))')
    local profs; profs="$(printf '%s' "$rj" | python3 -c 'import sys,json;print(",".join(json.load(sys.stdin)["profiles"]))')"
    [[ -n "$profs" ]] && { export COMPOSE_PROFILES="$profs"; info "profiles enabled by closure: $profs"; }
    # A clone always needs its ingress + DB viewer (nothing depends_on them).
    services+=(traefik whodb)
    info "resolved seed closure → ${#services[@]} services: ${services[*]}"
  fi

  # Changed = a listed service whose resolved context differs from ../<svc>.
  # Each gets image clode-stack/<svc>:<branch> and is rebuilt; the rest reuse
  # the baseline image.
  declare -A CHANGED_TAG=()
  local changed_svcs=()
  local svc dir base branch tag realdir realbase
  for svc in "${!WS_DIR[@]}"; do
    dir="${WS_DIR[$svc]}"; base="../$svc"
    [[ "$svc" == ec2mock ]] && base="../ec2-docker-mock"
    realdir="$(realpath -m "$dir" 2>/dev/null || echo "$dir")"
    realbase="$(realpath -m "$base" 2>/dev/null || echo "$base")"
    [[ "$realdir" == "$realbase" ]] && continue
    [[ "${WS_STATUS[$svc]:-}" == "ok" ]] || die "changed service '$svc' → $dir has no Dockerfile"
    branch="$(git -C "$dir" rev-parse --abbrev-ref HEAD 2>/dev/null || echo detached)"
    branch="${branch//\//-}"
    tag="clode-stack/${svc}:${branch}"
    CHANGED_TAG[$svc]="$tag"
    changed_svcs+=("$svc")
  done

  # Buildable services (have a build: section) — pinned to baseline images so the
  # clone doesn't rebuild them under its own project-derived name.
  local buildable_json
  buildable_json="$(docker compose --project-directory "$STACK_DIR" -f "$STACK_DIR/docker-compose.yml" -f "$STACK_DIR/docker-compose.cache.yml" config --format json \
    | python3 -c 'import sys,json; d=json.load(sys.stdin); print(json.dumps([k for k,v in d["services"].items() if v.get("build")]))')"

  # Changed map: svc -> clone image tag (JSON), built explicitly to dodge quoting.
  local changed_json="{" first=1 s
  for s in "${changed_svcs[@]:-}"; do
    [[ -z "$s" ]] && continue
    (( first )) && first=0 || changed_json+=","
    changed_json+="\"$s\":\"${CHANGED_TAG[$s]}\""
  done
  changed_json+="}"

  # Generate the overlay.
  mkdir -p "$STACK_DIR/.forks"
  local overlay="$STACK_DIR/.forks/${name}.yml"
  _gen_overlay "$name" "$port" "$buildable_json" "$changed_json" > "$overlay"
  info "generated overlay: $overlay"

  # Validate it merges cleanly before doing anything.
  _compose "$name" "$overlay" config >/dev/null || die "generated overlay failed to validate"

  # Build only the changed services (from their worktrees, tagged for the clone).
  if (( ${#changed_svcs[@]} > 0 )); then
    info "building changed services from feature branches: ${changed_svcs[*]}"
    DOCKER_BUILDKIT=1 _compose "$name" "$overlay" build "${changed_svcs[@]}"
  else
    info "no changed services — clone reuses baseline images entirely"
  fi

  info "starting clone '$name' (network=$name, traefik host port=$port)"
  _compose "$name" "$overlay" up -d "${services[@]}"

  echo
  info "clone '$name' up. Entry points (all on host port $port):"
  echo "    console/services : http://<svc>.localhost:$port   (e.g. http://brahmi.localhost:$port)"
  echo "    db viewer (WhoDB): http://whodb.localhost:$port"
  echo "    traefik dashboard: http://traefik.localhost:$port"
  echo "    status : docker compose -p $name ps"
  echo "    stop   : stack fork-down $name"
  _compose "$name" "$overlay" ps --format 'table {{.Service}}\t{{.Status}}' 2>/dev/null || true
}

# ─────────────────────────────────────────────────────────────── fork down ─
cmd_down() {
  local name="${1:-}"
  [[ -n "$name" ]] || die "usage: stack fork-down <name>"
  [[ "$name" == "clode" ]] && die "refusing to tear down the baseline 'clode' project"
  local overlay="$STACK_DIR/.forks/${name}.yml"
  if [[ -f "$overlay" ]]; then
    info "tearing down clone '$name' (containers + volumes + network)"
    _compose "$name" "$overlay" down -v --remove-orphans || true
    rm -f "$overlay"
  else
    # Overlay gone but project may still exist — down by project name.
    info "no overlay found; tearing down project '$name' by name"
    docker compose -p "$name" down -v --remove-orphans || true
  fi
  info "clone '$name' removed"
}

# ───────────────────────────────────────────────────────────────── fork ls ─
cmd_ls() {
  local overlays=("$STACK_DIR"/.forks/*.yml)
  echo "CLONE            TRAEFIK PORT   NETWORK        STATUS"
  echo "---------------  -------------  -------------  ------------------"
  local f name port running
  for f in "${overlays[@]}"; do
    [[ -e "$f" ]] || continue
    name="$(basename "$f" .yml)"
    port="$(grep -oE '"[0-9]+:8080"' "$f" | head -1 | tr -d '"' | cut -d: -f1)"
    running="$(docker compose -p "$name" ps --status running -q 2>/dev/null | wc -l | tr -d ' ')"
    printf '%-15s  %-13s  %-13s  %s running\n' "$name" "${port:-?}" "$name" "$running"
  done
}

sub="${1:-}"; shift || true
case "$sub" in
  up)   cmd_up   "$@" ;;
  down) cmd_down "$@" ;;
  ls)   cmd_ls   "$@" ;;
  *)    die "unknown subcommand '$sub' (use: up | down | ls)" ;;
esac
