#!/usr/bin/env bash
# gen-build-cache.sh — pull each Go service's Dockerfile from ../<svc>/, inject
# BuildKit cache mounts on go-mod-download / go-build RUN lines, drop the
# result in ./build-cache/, and emit docker-compose.cache.yml that points each
# service's build.dockerfile at the transformed copy.
#
# Run every time before `docker compose up` (up.sh does this for you). The
# generated files are not source — they're rebuilt from upstream on every
# run, so the stack can never drift from the real Dockerfiles.
#
# LOCAL SEED INJECTION. Services listed in SEED_MIGRATION_DIRS with a
# matching seeds/<svc>-seed.sql get one extra RUN injected before their
# `go build`: it appends the seed SQL onto the LAST *.up.sql in the
# service's migrations dir, so the seed rides the //go:embed into the
# binary and `<svc> migrate` plants the rows on a fresh database itself —
# before `serve`'s boot validation can crashloop (the fresh-stack
# deadlock). No new migration version is created, so upstream numbering
# is never disturbed; databases that already applied the last migration
# skip it (they were seeded by scripts/seed.sh, which remains the
# idempotent backstop for cleanup/reseed). The upstream repo's working
# tree is never touched — the append happens inside the image build.

set -euo pipefail
cd "$(dirname "$0")/.."

# Workspace overrides: point a service's build context at a git worktree
# instead of ../<svc>. resolve_workspaces exports <SVC>_DIR (the same var the
# compose build.context interpolates); we read it below to find each
# Dockerfile. Called directly here too so `./stack.sh build-cache` honors
# workspaces.yaml even when up.sh didn't export the vars first.
source scripts/lib/workspaces.sh
resolve_workspaces || exit 2

ROOT="$(pwd -P)"
OUT_DIR="build-cache"
OVERRIDE="docker-compose.cache.yml"
SERVICES=(raksha jumbo brahmi pool-manager chil cha-ching toolkit-proxy mang-proxy skills-registry narnia narnia-workers)

# service → migrations dir (relative to the service's build context) for
# local-seed injection. Add a line here + seeds/<svc>-seed.sql to give
# another service a build-time seed.
declare -A SEED_MIGRATION_DIRS=(
  [raksha]="db/migrations"
  [cha-ching]="internal/db/migrations"
)

mkdir -p "$OUT_DIR"

inject_mounts() {
  local src=$1 dst=$2 seed_file=${3:-} mig_dir=${4:-}
  python3 - "$src" "$dst" "$seed_file" "$mig_dir" <<'PYEOF'
import re, sys
src, dst = sys.argv[1], sys.argv[2]
seed_file, mig_dir = sys.argv[3], sys.argv[4]
# Shared `id=` keys so every service reuses ONE go-mod / go-build cache.
# Without `id`, BuildKit derives the cache key from target + Dockerfile path,
# giving each service its own ~1.5 GB duplicate of glafa / aws-sdk / chi /
# etc. — ~21 GB total across the stack. With the shared ids it collapses
# to one pool (~2–3 GB). `sharing=locked` serializes writers so parallel
# builds (--batch >1) don't race during `go mod download`.
mounts = (
    "--mount=type=cache,target=/go/pkg/mod,id=clode-go-mod,sharing=locked "
    "--mount=type=cache,target=/root/.cache/go-build,id=clode-go-build,sharing=locked "
)
# Build-time seed append (see file header). Emitted immediately before the
# FIRST `go build` RUN so the appended SQL is part of the //go:embed set.
# Quoted heredoc delimiter keeps the SQL byte-literal; the seed file bans
# a bare CLODE_SEED line.
seed_block = ''
if seed_file and mig_dir:
    seed_sql = open(seed_file).read().rstrip('\n')
    seed_block = (
        "# clode-stack: append local seed onto the last migration so `migrate`\n"
        "# itself seeds a fresh database (source: clode-stack/" + seed_file.split('/')[-2] + "/" + seed_file.split('/')[-1] + ")\n"
        'RUN cat >> "$(ls ' + mig_dir + '/*.up.sql | sort | tail -1)" <<\'CLODE_SEED\'\n'
        "\n" + seed_sql + "\nCLODE_SEED\n"
    )

lines = open(src).read().split('\n')
out, i, seed_done = [], 0, False
while i < len(lines):
    line = lines[i]
    if re.match(r'^\s*RUN\b', line):
        block = [line]
        while block[-1].rstrip().endswith('\\') and i + 1 < len(lines):
            i += 1
            block.append(lines[i])
        joined = '\n'.join(block)
        is_build = re.search(r'\bgo\s+build\b', joined)
        if is_build and seed_block and not seed_done:
            out.append(seed_block)
            seed_done = True
        if re.search(r'\bgo\s+mod\s+download\b', joined) or is_build:
            block[0] = re.sub(r'^(\s*RUN\s+)', r'\1' + mounts, block[0], count=1)
        out.extend(block)
    else:
        out.append(line)
    i += 1
if seed_block and not seed_done:
    sys.exit(f"gen-build-cache: no `go build` RUN found in {src} to anchor the seed injection")
open(dst, 'w').write('\n'.join(out))
PYEOF
}

{
  echo "# AUTO-GENERATED by gen-build-cache.sh — do not edit."
  echo "# Regenerated every ./stack.sh up from ../<svc>/Dockerfile."
  echo "services:"
} > "$OVERRIDE"

for svc in "${SERVICES[@]}"; do
  # Build context honors a workspace override (<SVC>_DIR), else ../<svc>.
  ctx_var="$(_ws_var "$svc")"
  ctx="${!ctx_var:-$(_ws_base "$svc")}"
  src="$ctx/Dockerfile"
  dst="$OUT_DIR/$svc.Dockerfile"
  if [[ ! -f "$src" ]]; then
    echo "warn: $src not found, skipping"
    continue
  fi
  seed_file="seeds/${svc}-seed.sql"
  mig_dir="${SEED_MIGRATION_DIRS[$svc]:-}"
  if [[ -n "$mig_dir" && -f "$seed_file" ]]; then
    inject_mounts "$src" "$dst" "$seed_file" "$mig_dir"
    echo "    + ${svc}: local seed appended to last migration (${seed_file})"
  else
    inject_mounts "$src" "$dst"
  fi
  # dockerfile is resolved by compose RELATIVE TO the build context. With a
  # worktree override the context can sit at any depth, so compute the
  # relative hop from the context back to the generated Dockerfile rather
  # than assuming the sibling-of-clode-stack layout. For the default
  # context (../$svc) this yields the historical ../clode-stack/... path.
  dockerfile_rel="$(realpath -m --relative-to="$ctx" "$ROOT/$OUT_DIR/$svc.Dockerfile")"
  cat >> "$OVERRIDE" <<EOF
  $svc:
    build:
      dockerfile: $dockerfile_rel
EOF
done

echo "==> regenerated $OUT_DIR/ + $OVERRIDE from upstream Dockerfiles (${#SERVICES[@]} services)"
