#!/usr/bin/env python3
"""
seed-skills-from-local.py — emits SQL that UPSERTs the aramb-skills repo +
every SKILL.md found under a local clone into clode-stack's skills-registry
database. Pipe the output to psql.

Why a script instead of `/api/v1/me/import`:
- The HTTP import endpoint walks the repo via the GitHub API (anonymous,
  60 req/hr) — gets rate-limited fast and the seeder fails.
- We already have the repo on disk; parsing it locally avoids the network
  entirely and is faster.

Inputs:
- ../aramb-skills           checked-out repo (run `git checkout main && git pull` first)
- data/skill-overrides.json column overrides (category/tags/etc.) per slug
- ADMIN_USER_ID env var      seeded as the user_id (importing user)

Output:
- SQL on stdout. Wrapped in a single transaction. Idempotent — uses
  INSERT ... ON CONFLICT DO UPDATE.

Failure modes:
- Missing/bad frontmatter on a SKILL.md → emits a SQL comment, skips that skill.
- Missing override slug → defaults apply, category/tags fall through to NULL/{}.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
SKILLS_REPO = (SCRIPT_DIR / ".." / ".." / "aramb-skills").resolve()
OVERRIDES_PATH = SCRIPT_DIR / ".." / "data" / "skill-overrides.json"

ADMIN_USER_ID = os.environ.get("ADMIN_USER_ID", "").strip()
if not ADMIN_USER_ID:
    sys.exit("error: ADMIN_USER_ID env var is required")


def sh(*args: str, cwd: Path | None = None) -> str:
    return subprocess.check_output(args, cwd=cwd, text=True).strip()


def sql_literal(v) -> str:
    """SQL literal — single-quote strings, NULL for None, dollar-quote big text."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    # Pick a dollar-quote tag that doesn't appear in s
    if len(s) > 200 or "\n" in s or "'" in s:
        tag = "BODY"
        while f"${tag}$" in s:
            tag += "X"
        return f"${tag}${s}${tag}$"
    return "'" + s.replace("'", "''") + "'"


def sql_text_array(items: list[str]) -> str:
    if not items:
        return "ARRAY[]::text[]"
    inner = ",".join(sql_literal(x) for x in items)
    return f"ARRAY[{inner}]::text[]"


def parse_skill_md(path: Path) -> tuple[dict, str]:
    raw = path.read_text(encoding="utf-8")
    if not raw.startswith("---"):
        raise ValueError(f"{path}: no YAML frontmatter")
    # Find the closing '---' on its own line
    lines = raw.split("\n")
    end_idx = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end_idx = i
            break
    if end_idx is None:
        raise ValueError(f"{path}: unterminated YAML frontmatter")
    fm = yaml.safe_load("\n".join(lines[1:end_idx])) or {}
    body = "\n".join(lines[end_idx + 1 :]).lstrip("\n")
    return fm, body


def main() -> None:
    config = json.loads(OVERRIDES_PATH.read_text())
    repo = config["_repo"]
    defaults = config["_defaults"]
    per_skill = config.get("skills", {})

    commit_sha = sh("git", "rev-parse", "HEAD", cwd=SKILLS_REPO)
    repo_id = repo["id"]

    out: list[str] = []
    out.append("-- generated by seed-skills-from-local.py — do not edit\nBEGIN;\n")

    # repos UPSERT
    out.append(
        "INSERT INTO repos (id, owner, name, url, license, stars, forks, "
        "owner_name, owner_url, owner_avatar_url, skills_path, last_parsed_at)\n"
        "VALUES (" + ",".join([
            sql_literal(repo_id),
            sql_literal(repo["owner"]),
            sql_literal(repo["name"]),
            sql_literal(repo.get("url")),
            sql_literal(repo.get("license")),
            "0", "0",
            sql_literal(repo.get("owner_name")),
            sql_literal(repo.get("owner_url")),
            sql_literal(repo.get("owner_avatar_url")),
            sql_literal(repo.get("skills_path", "")),
            "NOW()",
        ]) + ")\n"
        "ON CONFLICT (id) DO UPDATE SET\n"
        "    url=EXCLUDED.url, license=EXCLUDED.license,\n"
        "    owner_name=EXCLUDED.owner_name, owner_url=EXCLUDED.owner_url,\n"
        "    owner_avatar_url=EXCLUDED.owner_avatar_url,\n"
        "    last_parsed_at=NOW(), updated_at=NOW();\n"
    )

    skill_count = 0
    skipped: list[str] = []

    for entry in sorted(SKILLS_REPO.iterdir()):
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        skill_md = entry / "SKILL.md"
        if not skill_md.exists():
            continue

        slug = entry.name
        try:
            fm, body = parse_skill_md(skill_md)
        except Exception as exc:
            out.append(f"-- skip {slug}: {exc}\n")
            skipped.append(slug)
            continue

        ov = per_skill.get(slug, {})

        def pick(key: str, *fallbacks):
            for src in (ov, fm, defaults):
                if key in src and src[key] is not None:
                    return src[key]
            for fb in fallbacks:
                if fb is not None:
                    return fb
            return None

        name = pick("name", slug)
        description = pick("description") or ""
        license_ = pick("license")
        compatibility = pick("compatibility")
        allowed_tools = pick("allowed_tools") or fm.get("allowed-tools")
        category = pick("category")
        tags = ov.get("tags") if ov.get("tags") is not None else fm.get("tags") or []
        if isinstance(tags, str):
            tags = [t.strip() for t in tags.split(",") if t.strip()]

        full_id = f"{repo_id}/{slug}"
        source_url = defaults["source_url_template"].format(slug=slug)
        content_sha = hashlib.sha1(body.encode("utf-8")).hexdigest()  # VARCHAR(40)

        # file_tree — relative paths of every file in the skill dir
        files = sorted(
            str(p.relative_to(entry).as_posix())
            for p in entry.rglob("*")
            if p.is_file() and ".git" not in p.parts
        )
        file_tree = [{"path": f, "type": "blob"} for f in files]

        # skills UPSERT — declare the skill id with a CTE so skill_versions
        # can reference it within the same statement chain.
        out.append(
            f"\n-- {slug}\n"
            "WITH ins AS (\n"
            "  INSERT INTO skills (\n"
            "      owner_id, slug, full_id, name, description, license, compatibility,\n"
            "      allowed_tools, source_type, source_url, status, repo_id,\n"
            "      author_name, author_url, author_avatar_url, author_slug,\n"
            "      category, tags, user_id, is_private\n"
            "  ) VALUES (\n      "
            + ",\n      ".join([
                sql_literal(defaults["owner_id"]),
                sql_literal(slug),
                sql_literal(full_id),
                sql_literal(name),
                sql_literal(description),
                sql_literal(license_),
                sql_literal(compatibility),
                sql_literal(allowed_tools),
                sql_literal(defaults["source_type"]),
                sql_literal(source_url),
                sql_literal(defaults["status"]),
                sql_literal(repo_id),
                sql_literal(defaults["author_name"]),
                sql_literal(defaults["author_url"]),
                sql_literal(defaults["author_avatar_url"]),
                sql_literal(defaults["author_slug"]),
                sql_literal(category),
                sql_text_array(tags),
                sql_literal(ADMIN_USER_ID),
                "FALSE",
            ])
            + "\n  )\n"
            "  ON CONFLICT (full_id) DO UPDATE SET\n"
            "      name=EXCLUDED.name, description=EXCLUDED.description,\n"
            "      license=EXCLUDED.license, compatibility=EXCLUDED.compatibility,\n"
            "      allowed_tools=EXCLUDED.allowed_tools,\n"
            "      source_url=EXCLUDED.source_url, status=EXCLUDED.status,\n"
            "      category=EXCLUDED.category, tags=EXCLUDED.tags,\n"
            "      updated_at=NOW(), published_at=COALESCE(skills.published_at, NOW())\n"
            "  RETURNING id\n"
            ")\n"
            "INSERT INTO skill_versions (\n"
            "    skill_id, version, instructions, metadata, is_latest, is_draft,\n"
            "    content_sha, commit_sha, file_tree, file_tree_synced_at, published_at\n"
            ") SELECT id, 'v1', "
            + sql_literal(body) + ", '{}'::jsonb, TRUE, FALSE, "
            + sql_literal(content_sha) + ", " + sql_literal(commit_sha) + ", "
            + sql_literal(json.dumps(file_tree)) + "::jsonb, NOW(), NOW()\n"
            "FROM ins\n"
            # Migration 0007 replaced UNIQUE(skill_id,version) with a partial
            # unique index — ON CONFLICT must include the matching WHERE.
            "ON CONFLICT (skill_id, version) WHERE version IS NOT NULL DO UPDATE SET\n"
            "    instructions=EXCLUDED.instructions, content_sha=EXCLUDED.content_sha,\n"
            "    commit_sha=EXCLUDED.commit_sha, file_tree=EXCLUDED.file_tree,\n"
            "    file_tree_synced_at=NOW();\n"
        )
        skill_count += 1

    out.append("\nCOMMIT;\n")
    # \echo prints to psql's stdout, so seed.sh can grep for it; a `--`
    # comment would be silently consumed by psql.
    out.append(
        f"\\echo -- summary: {skill_count} skills, commit_sha={commit_sha}, "
        f"skipped={skipped or '[]'}\n"
    )
    sys.stdout.write("".join(out))


if __name__ == "__main__":
    main()
